<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DocuFlow.Contracts/DocuFlow.Contracts.csproj" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.103.7" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.103.2" />
    <PackageReference Include="AWSSDK.SimpleEmailV2" Version="4.0.104.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.12" />
  </ItemGroup>
</Project>
